### ISSUE TITLE
Fix regex101 problem

### ISSUE THREAD

**Issue by Vec7or** [Chexxo/Chexxo#31]
- Chexxo does not get triggered when opening https://regex101.com

**Comment by Yunnigg** [comment]
Problem also occurs with: https://addons.mozilla.org/de/firefox/

**Comment by Vec7or** [comment]
Nur in Firefox. Konnte in Chrome nicht nachvollzogen werden für keine der Beiden Seiten.

**Comment by Vec7or** [comment]
receiveWebRequest is not being called by either of the pages mentioned

**Comment by Vec7or** [comment]
Without the `types: ["main_frame"]` filter in WebRequest the EventManager gets called.

**Comment by Vec7or** [comment]
I do currently not see a mitigation for this.

**Comment by Yunnigg** [comment]
Will not be implemented:

- regex101.com is presumably a PWA, which prevents the extension to get any certificate information after the first request, since it is cached and likely never requested again.

- addons.mozilla.org is never requested from the browser via https, since it is most likely built into the browser.
